export const menu = [
  {
    id: 1,
    title: "Spaghetti bolognese",
    price: "159 NOK",
    ingredients: "Spaghetti, meat sauce, parmesan",
    category: "Main course",
  },
  {
    id: 2,
    title: "Creamy chicken soup",
    price: "129 NOK",
    ingredients: "Chicken, cream, carrots, celery",
    category: "Starter",
  },
  {
    id: 3,
    title: "Margherita pizza",
    price: "169 NOK",
    ingredients: "Tomato sauce, mozzarella, basil",
    category: "Main course",
  },
  {
    id: 4,
    title: "Sushi mix",
    price: "229 NOK",
    ingredients: "Salmon, tuna, shrimp, rice",
    category: "Main course",
  },
  {
    id: 5,
    title: "Caesar salad",
    price: "139 NOK",
    ingredients: "Romaine lettuce, chicken, parmesan, dressing",
    category: "Starter",
  },
  {
    id: 6,
    title: "Brownie with ice cream",
    price: "89 NOK",
    ingredients: "Brownie, vanilla ice cream, chocolate sauce",
    category: "Dessert",
  },
  {
    id: 7,
    title: "Taco plate",
    price: "199 NOK",
    ingredients: "Minced meat, corn, cheese, guacamole",
    category: "Main course",
  },
  {
    id: 8,
    title: "Pancakes with jam",
    price: "99 NOK",
    ingredients: "Pancakes, strawberry jam, sugar",
    category: "Dessert",
  },
  {
    id: 9,
    title: "Shrimp with lemon",
    price: "149 NOK",
    ingredients: "Shrimp, lemon, dill, bread",
    category: "Starter",
  },
  {
    id: 10,
    title: "Entrecôte with vegetables",
    price: "289 NOK",
    ingredients: "Entrecôte, asparagus, potatoes, pepper sauce",
    category: "Main course",
  },
];
